# The URL the site will be built for
base_url = "https://linnenberg.dev"

# Used in RSS by default
title = "linnenberg.dev"
description = "Personal blog of Ferdinand Linnenberg"

# The default language, used in RSS
default_language = "en"

# Theme to use
theme = "terminus"

# Whether to generate a RSS feed automatically
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Enable minification of HTML, CSS, and JS
minify_html = true

# Built in taxonomies
taxonomies = [
    {name = "tags"},
    {name = "categories"},
]

[extra]
# Author name
author = "Ferdinand Linnenberg"

# Copyright notice
 copyright = "Â© $YEAR $AUTHOR :: Powered by [Zola](https://www.getzola.org) :: Based on [Terminus Theme](https://github.com/ebkalderon/terminus) by [ebkalderon](https://eyalkalderon.com)"

# Layout option: "center", "left", or "full-width"
layout = "center"

# Display default author on all pages
show_default_author = true

# Add copy button to code blocks
copy_button = true

# Main menu
main_menu = [
    { name = "home", url = "", trailing_slash = true },
    { name = "cv", url = "cv-en", trailing_slash = true },
    { name = "contact", url = "contact", trailing_slash = true },
    { name = "uses", url = "uses", trailing_slash = true },
    { name = "github", url = "https://github.com/Scarjit", trailing_slash = true },
    { name = "dn42", url = "dn42", trailing_slash = true },
]

# Social links
socials = [
    { name = "email", url = "mailto:ferdinand@linnenberg.dev" },
    { name = "github", url = "https://github.com/Scarjit" },
    { name = "linkedin", url = "https://www.linkedin.com/in/ferdinand-l-b1124321b" },
    { name = "keybase", url = "https://keybase.io/scarjit" },
]

[extra.content_security_policy]
enable = true
allowed_domains = ["linnenberg.dev"]

[extra.responsive_images]
widths = [640, 784, 1280, 1920, 2560]
fallback_width = 1280